name: Generate Test Summary

on:
  workflow_dispatch:

jobs:
  generate-summary:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run script to generate summary
        run: python generate_summary.py test_report.json >> $GITHUB_STEP_SUMMARY
