name: Job Action Summary


on:
  push:
    branches:
      - main

jobs:
  Summary:
    name: Summary
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests and capture results
        run: |
          python -m pytest tests --cov=. --cov-report xml:coverage.xml --junitxml=test/results/TEST-results.xml

      - name: Run tests and generate JSON report
        run: |
          python -m pytest --json-report --json-report-file=test_report.json

      - name: Generate test summary
        run: python generate_summary.py

      - name: Append summary to GitHub Actions summary
        run: cat test_summary.md >> $GITHUB_STEP_SUMMARY
