name: Supercharging GitHub Actions with Job Summaries

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Adding Markdown
      run: echo '### Hello world! 🚀' >> $GITHUB_STEP_SUMMARY
