name: HTML Preview


on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - main
jobs:
  preview:
    runs-on: ubuntu-latest  # Specify the runner environment

    steps:
      - uses: actions/checkout@v3  # Checkout the repository code

      - uses: pavi2410/html-preview-action@v2  # Use the HTML Preview Action
        with:
          html_file: 'index.html'  # Path to your HTML file (replace with your filename)

      - name: Share Preview Link  # Optional step to print the URL
        run: |
          echo "Preview URL: ${{ steps.html_preview.outputs.url }}"
